export const EVENTOS_ESTADO = {

  EXPLORACION_FALLIDA: 'HERIDO',

  MORDIDA_ZOMBIE: 'INFECTADO',

  ENFERMEDAD: 'ENFERMO',

  FATIGA_EXTREMA: 'AGOTADO',

  MUERTE: 'MUERTO',

  EXPLORACION_ACTIVA: 'EN_MISION'
};